/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.h
  * @brief          : Header for main.c file.
  *                   This file contains the common defines of the application.
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */

/*
 * ============================================================
 * [LCD - DO NOT MODIFY]: This file is owned by the LCD Engineer.
 * It is AUTO-GENERATED by STM32CubeMX and must not be hand-edited
 * by other team members.  Regenerating from CubeMX will overwrite
 * any changes made outside the USER CODE sections.
 *
 * FILE: main.h
 * OWNER: LCD Engineer
 *
 * PURPOSE:
 *   Central hardware configuration header.  Defines all GPIO pin
 *   assignments for the STM32G071 on this board.  Included by every
 *   source file that needs to reference hardware pins.
 *
 * PIN SUMMARY:
 *   BTN_CALIBRATE  PC13 — onboard blue push-button (shared by calibration & selftest)
 *   MCO            PF0  — clock output pin (unused by application firmware)
 *   USART2_TX      PA2  — serial transmit  (debug / printf redirect)
 *   USART2_RX      PA3  — serial receive
 *   LED_GREEN      PA5  — onboard green LED (LD2, not actively driven by firmware)
 *   ST7789_DC      PA9  — LCD data/command select
 *   TMS            PA13 — SWD debug interface (JTAG TMS)
 *   TCK            PA14 — SWD debug interface (JTAG TCK)
 *   ST7789_RST     PC7  — LCD hardware reset (active low)
 *   ST7789_CS      PB6  — LCD SPI chip select (active low)
 * ============================================================
 */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32g0xx_hal.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */

/* USER CODE END Includes */

/* Exported types ------------------------------------------------------------*/
/* USER CODE BEGIN ET */

/* USER CODE END ET */

/* Exported constants --------------------------------------------------------*/
/* USER CODE BEGIN EC */

/* USER CODE END EC */

/* Exported macro ------------------------------------------------------------*/
/* USER CODE BEGIN EM */

/* USER CODE END EM */

/* Exported functions prototypes ---------------------------------------------*/
void Error_Handler(void);

/* USER CODE BEGIN EFP */

/* USER CODE END EFP */

/* Private defines -----------------------------------------------------------*/
/* User push-button on the NUCLEO board. Active HIGH (pulled low at rest).
 * Used by both Stage 1 (calibration) and Stage 2 (self-test). */
#define BTN_CALIBRATE_Pin GPIO_PIN_13
#define BTN_CALIBRATE_GPIO_Port GPIOC

/* MCO — Microcontroller Clock Output pin. Not used by application firmware. */
#define MCO_Pin GPIO_PIN_0
#define MCO_GPIO_Port GPIOF

/* USART2 TX/RX — available for printf-style debug output over ST-Link virtual COM.
 * Not actively used by the step tracker application. */
#define USART2_TX_Pin GPIO_PIN_2
#define USART2_TX_GPIO_Port GPIOA
#define USART2_RX_Pin GPIO_PIN_3
#define USART2_RX_GPIO_Port GPIOA

/* Onboard green LED (LD2). Not actively driven by the current firmware. */
#define LED_GREEN_Pin GPIO_PIN_5
#define LED_GREEN_GPIO_Port GPIOA

/* ST7789 LCD — Data/Command select. HIGH = data, LOW = command (register write). */
#define ST7789_DC_Pin GPIO_PIN_9
#define ST7789_DC_GPIO_Port GPIOA

/* ST7789 LCD — Hardware reset. Active LOW: pull low briefly to reset the LCD controller. */
#define ST7789_RST_Pin GPIO_PIN_7
#define ST7789_RST_GPIO_Port GPIOC

/* SWD debug interface — do not use these pins for GPIO in application code. */
#define TMS_Pin GPIO_PIN_13
#define TMS_GPIO_Port GPIOA
#define TCK_Pin GPIO_PIN_14
#define TCK_GPIO_Port GPIOA

/* ST7789 LCD — SPI chip select. Active LOW: pull low before sending SPI data. */
#define ST7789_CS_Pin GPIO_PIN_6
#define ST7789_CS_GPIO_Port GPIOB

/* USER CODE BEGIN Private defines */

/* USER CODE END Private defines */

#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H */
